# Generated by Django 2.2 on 2019-04-13 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(default=0)),
                ('stipend', models.IntegerField(default=0)),
                ('admin_remark', models.CharField(default='', max_length=500)),
                ('profile_image', models.ImageField(upload_to='profile_image')),
                ('offer_letter', models.FileField(upload_to='uploads/')),
                ('date_of_joining', models.DateField()),
                ('date_of_leaving', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
