# Generated by Django 2.2 on 2019-04-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_joining',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_leaving',
            field=models.DateField(blank=True),
        ),
    ]
