# Generated by Django 2.2 on 2019-04-13 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190413_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='offer_letter',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(upload_to='profile_image/'),
        ),
    ]
