# Generated by Django 2.2 on 2019-04-14 02:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190413_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_joining',
            field=models.DateField(default=datetime.date(2019, 4, 14)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_leaving',
            field=models.DateField(default=datetime.date(2019, 4, 14)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='offer_letter',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profile_image/'),
        ),
    ]
