# Generated by Django 2.2 on 2019-04-14 02:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190414_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_joining',
            field=models.DateField(default=datetime.datetime(2019, 4, 14, 2, 39, 15, 892958, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_leaving',
            field=models.DateField(default=datetime.datetime(2019, 4, 14, 2, 39, 15, 892958, tzinfo=utc)),
        ),
    ]
