# Generated by Django 2.2 on 2019-04-14 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190414_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_leaving',
            field=models.DateField(blank=True, null=True),
        ),
    ]
