# Generated by Django 2.2 on 2019-04-14 03:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190414_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_joining',
            field=models.DateField(default=datetime.datetime(2019, 4, 14, 3, 22, 34, 956823, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_leaving',
            field=models.DateField(default=datetime.datetime(2019, 4, 14, 3, 22, 34, 956823, tzinfo=utc)),
        ),
    ]
